version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: laravel-app
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel_rent_car_new
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      back_net_app:
        aliases:
          - app

  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_rent_car_new
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      back_net_app:
        aliases:
          - db

  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    networks:
      back_net_app:
        aliases:
          - nginx
    depends_on:
      - app

volumes:
  db_data:

networks:
  back_net_app:
    external: false
    driver: bridge
